# Generated by Django 6.0 on 2025-12-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('entry', models.FloatField()),
                ('stop', models.FloatField()),
                ('target', models.FloatField()),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
