# Generated by Django 6.0 on 2025-12-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
